import { useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, Info, CheckCircle2 } from "lucide-react";
import styles from "./MakeConnect.module.scss";
import ActionButton from "../ActionButton/ActionButton";
import AppIcon from "../AppIcon/AppIcon";
import Dropdown from "../Dropdown/Dropdown";

export default function MakeConnect() {
  const { getToken } = useAuth();
  const navigate = useNavigate();

  // The 2-Step State
  const [step, setStep] = useState<1 | 2>(1);

  // Form State
  const [apiKey, setApiKey] = useState("");
  const [label, setLabel] = useState("");
  const [zone, setZone] = useState("us1");

  const [status, setStatus] = useState<{
    type: "idle" | "loading" | "success" | "error";
    message: string;
  }>({ type: "idle", message: "" });

  const zoneOptions = [
    { label: "US1 (us1.make.com)", value: "us1" },
    { label: "US2 (us2.make.com)", value: "us2" },
    { label: "EU1 (eu1.make.com)", value: "eu1" },
    { label: "EU2 (eu2.make.com)", value: "eu2" },
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus({ type: "loading", message: "Verifying with Make.com..." });

    try {
      const token = await getToken();
      const response = await fetch(
        `${import.meta.env.VITE_API_BASE_URL}/api/MakeConnections`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            apiKey: apiKey,
            label: label || `${zone.toUpperCase()} Connection`,
            zone: zone,
          }),
        },
      );

      if (response.ok) {
        setStatus({
          type: "success",
          message: "Success! Key verified and securely saved.",
        });

        // Transition Logic
        setTimeout(() => {
          if (step === 1) {
            // Move to Step 2, clear form, and default to the other region
            setStep(2);
            setApiKey("");
            setLabel("");
            setZone(zone.startsWith("us") ? "eu1" : "us1");
            setStatus({ type: "idle", message: "" });
          } else {
            // They finished adding their second key, go to app
            navigate("/scenarios");
          }
        }, 1500);
      } else {
        const errorText = await response.text();
        setStatus({ type: "error", message: errorText });
      }
    } catch (err: any) {
      setStatus({
        type: "error",
        message: "Network error. Make sure the backend is running.",
      });
    }
  };

  const handleSkip = () => {
    navigate("/scenarios");
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2 className={styles.title}>
          <AppIcon accountName="Make" />
          {step === 1 ? "Connect Make.com" : "Add Secondary Workspace"}
        </h2>
        <p className={styles.description}>
          {step === 1
            ? "Connect your Base workspace. We will encrypt your token and securely link it to your vault."
            : "Do you have workspaces in other regions (e.g., US vs EU) that you want to compare? If so, you will need a separate API key generated by a workspace owner in that region."}
        </p>
      </div>

      {step === 1 && (
        <>
          <div className={`${styles.alertBox} ${styles.infoAlert}`}>
            <Info size={20} style={{ flexShrink: 0, marginTop: "2px" }} />
            <div className={styles.alertContent}>
              <strong>Working across US & EU servers?</strong>
              You will need a separate API key for each zone. We will connect
              your first one now, and you can add your second one on the next
              screen.
            </div>
          </div>
        </>
      )}

      {step === 2 && (
        <div className={`${styles.alertBox} ${styles.successAlert}`}>
          <CheckCircle2 size={20} style={{ flexShrink: 0, marginTop: "2px" }} />
          <div className={styles.alertContent}>
            <strong>First connection successful!</strong>
            Your base workspace is ready. You can add a secondary zone now, or
            skip and go straight to the deployment console.
          </div>
        </div>
      )}

      <form className={styles.form} onSubmit={handleSubmit}>
        <div className={styles.inputGroup}>
          <label className={styles.label}>Server Zone</label>
          <Dropdown
            options={zoneOptions}
            value={zone}
            onChange={(val) => setZone(val as string)}
            size="lg"
          />
        </div>

        <div className={styles.inputGroup}>
          <label className={styles.label} htmlFor="labelInput">
            Connection Label
          </label>
          <input
            id="labelInput"
            type="text"
            className={styles.input}
            placeholder={
              step === 1 ? "e.g., Acme Agency US" : "e.g., Acme Agency EU"
            }
            value={label}
            onChange={(e) => setLabel(e.target.value)}
          />
        </div>

        <div className={styles.inputGroup}>
          <label className={styles.label} htmlFor="apiKeyInput">
            Make.com API Key
          </label>
          <input
            id="apiKeyInput"
            type="password"
            className={styles.input}
            placeholder="8f72a9b3-..."
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
            required
          />
        </div>

        {step === 1 ? (
          <ActionButton
            title={status.type === "loading" ? "Verifying..." : "Connect"}
            variant="primary"
            disabled={status.type === "loading" || !apiKey}
            type="submit"
            size="lg"
          />
        ) : (
          <div className={styles.buttonGroup}>
            <ActionButton
              title="Skip for now"
              variant="secondary"
              onClick={handleSkip}
              type="button"
              size="lg"
            />
            <ActionButton
              title={
                status.type === "loading"
                  ? "Verifying..."
                  : "Add Second Connection"
              }
              variant="primary"
              disabled={status.type === "loading" || !apiKey}
              type="submit"
              size="lg"
            />
          </div>
        )}
      </form>

      {status.type !== "idle" && status.type !== "loading" && (
        <div
          className={`${styles.status} ${status.type === "success" ? styles.success : styles.error}`}
        >
          {status.message}
        </div>
      )}
    </div>
  );
}
